include classpath("application.conf")

node-address {
  protocol = http
  host = "*"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

queues {
  imgopt-optimize {
    defaultVisibilityTimeout = 300 seconds
    receiveMessageWait = 0 seconds
    deadLettersQueue {
      name = "imgopt-optimize-dlq"
      maxReceiveCount = 3
    }
  }
  imgopt-optimize-dlq { }
}
